
CREATE TABLE IF NOT EXISTS tbluser (
    id SERIAL PRIMARY KEY,
    email VARCHAR(120) UNIQUE NOT NULL,
    fullName VARCHAR(50) NOT NULL,
    password TEXT NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tblaccount (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES tbluser(id) ON DELETE CASCADE,
    account_name VARCHAR(50) NOT NULL,
    account_number VARCHAR(50) NOT NULL,
    account_balance NUMERIC(10,2) NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tblcategory (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    type VARCHAR(10) NOT NULL, -- 'income' or 'expense'
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS tbltransaction (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES tbluser(id) ON DELETE CASCADE,
    account_id INTEGER REFERENCES tblaccount(id) ON DELETE SET NULL,
    category_id INTEGER REFERENCES tblcategory(id) ON DELETE SET NULL,
    description TEXT NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'Pending',
    source VARCHAR(100) NOT NULL,
    amount NUMERIC(10,2) NOT NULL,
    type VARCHAR(10) NOT NULL DEFAULT 'income', -- 'income' or 'expense'
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- {
--   "email" :"rithiga2026@gmail.com",
--   "fullname":"Rithiga",
--   "password":"12"
  
-- }